<a href="https://colab.research.google.com/github/vishalsingh816/customer_churn/blob/main/DomainTraining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
abcd = np.array([1,2,3,4])
print(abcd.dtype)


int64


In [ ]:
aa = np.array(['ram', 'sita', 'ajay'])
print (aa.dtype)

<U4


In [ ]:
mm = np.array([1,4,6,8,10,15,16,17,18,19])
a=mm.reshape (2,5)
print (a)

[[ 1  4  6  8 10]
 [15 16 17 18 19]]


In [ ]:
a1=np.array([3,5,7,])
a2=np.array([5,6,4])
a=np.concatenate((a1,a2))
print (a)

[3 5 7 5 6 4]


In [ ]:
a3=np.array([[1,2],[4,5]])
a4=np.array([[7,8],[1,5]])
e=np.concatenate((a3,a4),axis=1)
print (e)

[[1 2 7 8]
 [4 5 1 5]]


In [ ]:
print ('VishaL')


VishaL


In [ ]:
d =np.array([[2,9],[5,6]])
v =np.resize(d,(5,2))
print(v)

[[2 9]
 [5 6]
 [2 9]
 [5 6]
 [2 9]]


In [ ]:
ay13=np.array([5,56,7,8])
print (np.sort(ay13))

[ 5  7  8 56]


In [ ]:
p=np.array(['d','o','g'])
print(np.sort(p))

['d' 'g' 'o']


In [ ]:
vk=np.array([1,40,3])
print (np.arange(vk))

NameError: ignored

In [ ]:
import numpy as np
a35=[0,1],[0,5]

In [ ]:
a38 = np.array([[0,1,2],[2,3,4]])
a39 = np.array([4,5,6])
print(np.add(a38,a39))

[[ 4  6  8]
 [ 6  8 10]]
